#!/usr/bin/env node
/**
 * Read agent/prompts/system.md at build time and emit it as a TypeScript constant.
 *
 * This is required for Bun's --compile mode: the system prompt becomes part of the
 * compiled binary instead of being read from disk at runtime, which means the
 * compiled agent doesn't need its prompt files shipped alongside it.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const promptPath = resolve(__dirname, "..", "prompts", "system.md");
const outputPath = resolve(__dirname, "..", "src", "system-prompt.generated.ts");

const content = await readFile(promptPath, "utf-8");

// Escape backticks and ${ for template literal embedding
const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const banner = `// AUTO-GENERATED by agent/scripts/embed-prompt.mjs — do not edit by hand.
// Source: agent/prompts/system.md
// Regenerated on every build; commit this file so non-Bun builds work too.
`;

const out = `${banner}
export const SYSTEM_PROMPT = \`${escaped}\`;
`;

await writeFile(outputPath, out, "utf-8");
console.log(`embedded ${content.length} chars from system.md → ${outputPath}`);
